import { 
  Property, 
  Contact, 
  Agreement, 
  Lead, 
  FollowupActivity, 
  SiteVisit, 
  Booking, 
  Closing, 
  CommissionRecord, 
  PublishingRecord, 
  Campaign 
} from '../types';

export const initialContacts: Contact[] = [
  {
    id: 'cnt-1',
    type: 'Owner',
    name: 'Ir. Hendra Gunawan',
    whatsapp: '6281234567890',
    phone: '0812-3456-7890',
    email: 'hendra.gunawan@gmail.com',
    propertiesCount: 2,
    activeAgreementsCount: 2,
    lastContact: '2026-09-24',
    status: 'Active',
    notes: 'Pemilik unit di Kaliurang & Seturan. Terbuka nego tipis, komisi standar 2.5% disetujui.',
    communicationHistory: [
      { id: 'ch-1', date: '2026-09-24', channel: 'WhatsApp', summary: 'Konfirmasi update foto properti & perpanjangan masa tayang iklan', agent: 'Dimas Aditya' },
      { id: 'ch-2', date: '2026-09-10', channel: 'Call', summary: 'Diskusi hasil survei calon buyer pertama Pak Budi', agent: 'Dimas Aditya' }
    ]
  },
  {
    id: 'cnt-2',
    type: 'Owner',
    name: 'Dr. Ratna Susanti',
    whatsapp: '6281987654321',
    phone: '0819-8765-4321',
    email: 'ratna.susanti@medika.org',
    propertiesCount: 1,
    activeAgreementsCount: 1,
    lastContact: '2026-09-25',
    status: 'Active',
    notes: 'Rumah keluarga di Condongcatur, Sleman. Sertifikat SHM on hand ready akad.',
    communicationHistory: [
      { id: 'ch-3', date: '2026-09-25', channel: 'WhatsApp', summary: 'Jadwal survei akhir pekan bersama prospek keluarga muda', agent: 'Siti Rahma' }
    ]
  },
  {
    id: 'cnt-3',
    type: 'Owner',
    name: 'Bambang Soediro',
    whatsapp: '6285611223344',
    phone: '0856-1122-3344',
    email: 'bambang.s@kreasiproperti.id',
    propertiesCount: 3,
    activeAgreementsCount: 1,
    lastContact: '2026-09-20',
    status: 'Follow Up',
    notes: 'Pemilik ruko Palagan & tanah kavling. Perlu perpanjangan perjanjian komisi.',
    communicationHistory: [
      { id: 'ch-4', date: '2026-09-20', channel: 'Meeting', summary: 'Pertemuan di kantor Honey-an review progress leads', agent: 'Dimas Aditya' }
    ]
  },
  {
    id: 'cnt-4',
    type: 'Agent',
    name: 'Fajar Nugroho (Mitra Broker)',
    whatsapp: '6282133445566',
    phone: '0821-3344-5566',
    email: 'fajar.broker@propertijogja.net',
    propertiesCount: 4,
    activeAgreementsCount: 2,
    lastContact: '2026-09-26',
    status: 'Active',
    notes: 'Mitra cobroke spesialis Sleman Barat & Bantul. Co-broking split komisi 50:50.',
    communicationHistory: [
      { id: 'ch-5', date: '2026-09-26', channel: 'WhatsApp', summary: 'Kirim listing baru cluster dekat Kampus UMY', agent: 'Rian Pratama' }
    ]
  }
];

export const initialProperties: Property[] = [
  {
    id: 'prop-1',
    code: 'HN-SLM-001',
    title: 'Rumah Modern Minimalis 2 Lantai Dekat Kampus UGM',
    propertyType: 'House',
    description: 'Rumah siap huni dengan pencahayaan alami optimal, interior elegan semi-furnished, berada dalam one gate system cluster dengan security 24 jam.',
    province: 'D.I. Yogyakarta',
    city: 'Sleman',
    district: 'Depok',
    subdistrict: 'Condongcatur',
    address: 'Jl. Kaliurang KM 6.5, Gang Pandega Marta No. 12',
    googleMapsUrl: 'https://maps.google.com/?q=-7.7554,110.3789',
    askingPrice: 880000000,
    minimumNegotiablePrice: 850000000,
    pricePerSqm: 7333333,
    landSize: 120,
    buildingSize: 105,
    bedrooms: 3,
    bathrooms: 2,
    floors: 2,
    carport: 2,
    electricity: '2200 VA',
    waterSource: 'Sumur Bor + Jetpump',
    certificateType: 'SHM',
    certificateNumber: 'SHM No. 04812/Condongcatur',
    pbgStatus: true,
    legalNotes: 'SHM & PBG lengkap atas nama perorangan, IMB ready, PBB lunas.',
    marketplace: 'Rumah123',
    originalListingUrl: 'https://rumah123.com/listing/hn-slm-001',
    originalListingId: 'R123-992384',
    dateCollected: '2026-09-01',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    propertyImages: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80'
    ],
    ownerId: 'cnt-1',
    ownerName: 'Ir. Hendra Gunawan',
    listingStatus: 'Ready to Market',
    agreementStatus: 'Active',
    leadCount: 14,
    siteVisitCount: 6,
    viewsCount: 3820,
    inquiriesCount: 48,
    potentialCommission: 22000000,
    createdAt: '2026-09-02'
  },
  {
    id: 'prop-2',
    code: 'HN-SLM-002',
    title: 'Cluster Scandinavian Asri Dekat RS JIH & Hartono Mall',
    propertyType: 'House',
    description: 'Rumah baru bernuansa skandinavia dengan taman depan dan belakang. Sirkulasi udara sangat sejuk, carport kanopi baja ringan sudah terpasang.',
    province: 'D.I. Yogyakarta',
    city: 'Sleman',
    district: 'Ngaglik',
    subdistrict: 'Sardonoharjo',
    address: 'Jl. Palagan Tentara Pelajar KM 9',
    googleMapsUrl: 'https://maps.google.com/?q=-7.7124,110.3892',
    askingPrice: 750000000,
    minimumNegotiablePrice: 720000000,
    pricePerSqm: 6818181,
    landSize: 110,
    buildingSize: 85,
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    carport: 1,
    electricity: '2200 VA',
    waterSource: 'PDAM',
    certificateType: 'SHM',
    certificateNumber: 'SHM No. 03211/Ngaglik',
    pbgStatus: true,
    legalNotes: 'Pecah SHM per kavling selesai, siap balik nama dan KPR.',
    marketplace: 'OLX',
    originalListingUrl: 'https://olx.co.id/item/cluster-scandinavian-palagan',
    originalListingId: 'OLX-882190',
    dateCollected: '2026-09-05',
    coverImage: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
    propertyImages: [
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80'
    ],
    ownerId: 'cnt-2',
    ownerName: 'Dr. Ratna Susanti',
    listingStatus: 'Published',
    agreementStatus: 'Active',
    leadCount: 19,
    siteVisitCount: 9,
    viewsCount: 5120,
    inquiriesCount: 62,
    potentialCommission: 18750000,
    createdAt: '2026-09-06'
  },
  {
    id: 'prop-3',
    code: 'HN-BTL-003',
    title: 'Rumah Tropis Modern View Persawahan Asri Kasihan',
    propertyType: 'House',
    description: 'Lingkungan tenang, udara segar, view hamparan sawah hijau. Akses mobil papasan, hanya 7 menit ke Kampus UMY Yogyakarta.',
    province: 'D.I. Yogyakarta',
    city: 'Bantul',
    district: 'Kasihan',
    subdistrict: 'Bangunjiwo',
    address: 'Jl. Bibis Raya, Bangunjiwo, Kasihan',
    googleMapsUrl: 'https://maps.google.com/?q=-7.8344,110.3211',
    askingPrice: 580000000,
    minimumNegotiablePrice: 550000000,
    pricePerSqm: 5800000,
    landSize: 100,
    buildingSize: 65,
    bedrooms: 2,
    bathrooms: 1,
    floors: 1,
    carport: 1,
    electricity: '1300 VA',
    waterSource: 'Sumur Bor',
    certificateType: 'SHM',
    certificateNumber: 'SHM No. 01844/Bangunjiwo',
    pbgStatus: true,
    legalNotes: 'Sertifikat hak milik aman, tidak dalam sengketa atau jaminan bank.',
    marketplace: 'Facebook Marketplace',
    originalListingUrl: 'https://facebook.com/marketplace/item/kasihan-view-sawah',
    originalListingId: 'FBM-449102',
    dateCollected: '2026-09-08',
    coverImage: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
    propertyImages: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    ownerId: 'cnt-4',
    ownerName: 'Fajar Nugroho (Mitra Broker)',
    listingStatus: 'Published',
    agreementStatus: 'Active',
    leadCount: 11,
    siteVisitCount: 4,
    viewsCount: 2900,
    inquiriesCount: 31,
    potentialCommission: 14500000,
    createdAt: '2026-09-09'
  },
  {
    id: 'prop-4',
    code: 'HN-YOG-004',
    title: 'Guesthouse / Rumah Mewah Heritage Dekat Malioboro',
    propertyType: 'Villa',
    description: 'Cocok untuk investasi homestay atau guesthouse dengan okupansi tinggi di pusat kota Yogyakarta. Lengkap dengan kolam renang mini.',
    province: 'D.I. Yogyakarta',
    city: 'Kota Yogyakarta',
    district: 'Danurejan',
    subdistrict: 'Bausasran',
    address: 'Jl. Bausasran No. 34, Danurejan',
    googleMapsUrl: 'https://maps.google.com/?q=-7.7944,110.3755',
    askingPrice: 3200000000,
    minimumNegotiablePrice: 3000000000,
    pricePerSqm: 12800000,
    landSize: 250,
    buildingSize: 220,
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    carport: 3,
    electricity: '4400 VA',
    waterSource: 'PDAM + Sumur',
    certificateType: 'SHM',
    certificateNumber: 'SHM No. 00891/Danurejan',
    pbgStatus: true,
    legalNotes: 'Izin guesthouse komersial siap pakai, kepemilikan tunggal.',
    marketplace: 'Direct Owner',
    originalListingUrl: '',
    originalListingId: 'DO-004',
    dateCollected: '2026-09-12',
    coverImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
    propertyImages: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80'
    ],
    ownerId: 'cnt-1',
    ownerName: 'Ir. Hendra Gunawan',
    listingStatus: 'Reserved',
    agreementStatus: 'Active',
    leadCount: 8,
    siteVisitCount: 5,
    viewsCount: 4100,
    inquiriesCount: 22,
    potentialCommission: 80000000,
    createdAt: '2026-09-12'
  },
  {
    id: 'prop-5',
    code: 'HN-SLM-005',
    title: 'Ruko Strategis 3 Lantai Pinggir Ringroad Utara Sleman',
    propertyType: 'Shophouse',
    description: 'Lokasi emas commercial strip Ringroad Utara, lalu lintas ramai 24 jam, area parkir luas hingga 6 mobil.',
    province: 'D.I. Yogyakarta',
    city: 'Sleman',
    district: 'Depok',
    subdistrict: 'Maguwoharjo',
    address: 'Ringroad Utara KM 10, Maguwoharjo',
    googleMapsUrl: 'https://maps.google.com/?q=-7.7612,110.4215',
    askingPrice: 2400000000,
    minimumNegotiablePrice: 2250000000,
    pricePerSqm: 16000000,
    landSize: 150,
    buildingSize: 280,
    bedrooms: 2,
    bathrooms: 3,
    floors: 3,
    carport: 4,
    electricity: '5500 VA',
    waterSource: 'PDAM',
    certificateType: 'HGB',
    certificateNumber: 'HGB No. 12903/Maguwo',
    pbgStatus: true,
    legalNotes: 'HGB murni berlaku hingga 2045, dapat ditingkatkan ke SHM.',
    marketplace: 'Lamudi',
    originalListingUrl: 'https://lamudi.co.id/ruko-maguwo-ringroad',
    originalListingId: 'LAM-332910',
    dateCollected: '2026-09-14',
    coverImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
    propertyImages: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
    ],
    ownerId: 'cnt-3',
    ownerName: 'Bambang Soediro',
    listingStatus: 'Owner Contacted',
    agreementStatus: 'Waiting Approval',
    leadCount: 4,
    siteVisitCount: 1,
    viewsCount: 1200,
    inquiriesCount: 12,
    potentialCommission: 60000000,
    createdAt: '2026-09-15'
  }
];

export const initialAgreements: Agreement[] = [
  {
    id: 'agr-1',
    code: 'AGR-2026-09-001',
    propertyId: 'prop-1',
    propertyTitle: 'Rumah Modern Minimalis 2 Lantai Dekat Kampus UGM',
    propertyCode: 'HN-SLM-001',
    ownerId: 'cnt-1',
    ownerName: 'Ir. Hendra Gunawan',
    agreementDate: '2026-09-02',
    expiryDate: '2026-12-02',
    commissionType: 'Percentage',
    commissionValue: 2.5,
    leadProtectionPeriodDays: 90,
    notes: 'Eksklusif marketing Honey-an selama 3 bulan. Jika buyer dibawa Honey-an bertransaksi setelah masa berlaku hingga 90 hari, komisi tetap berlaku.',
    status: 'Active',
    createdAt: '2026-09-02'
  },
  {
    id: 'agr-2',
    code: 'AGR-2026-09-002',
    propertyId: 'prop-2',
    propertyTitle: 'Cluster Scandinavian Asri Dekat RS JIH & Hartono Mall',
    propertyCode: 'HN-SLM-002',
    ownerId: 'cnt-2',
    ownerName: 'Dr. Ratna Susanti',
    agreementDate: '2026-09-06',
    expiryDate: '2026-12-06',
    commissionType: 'Percentage',
    commissionValue: 2.5,
    leadProtectionPeriodDays: 90,
    notes: 'Perjanjian semi-eksklusif. Pemasangan banner dan iklan bersponsor Meta didanai Honey-an.',
    status: 'Active',
    createdAt: '2026-09-06'
  },
  {
    id: 'agr-3',
    code: 'AGR-2026-09-003',
    propertyId: 'prop-4',
    propertyTitle: 'Guesthouse / Rumah Mewah Heritage Dekat Malioboro',
    propertyCode: 'HN-YOG-004',
    ownerId: 'cnt-1',
    ownerName: 'Ir. Hendra Gunawan',
    agreementDate: '2026-09-12',
    expiryDate: '2026-12-12',
    commissionType: 'Percentage',
    commissionValue: 2.5,
    leadProtectionPeriodDays: 120,
    notes: 'Komisi 2.5% dari harga realisasi deal final. Dokumen fisik ditandatangani bermaterai.',
    status: 'Active',
    createdAt: '2026-09-12'
  }
];

export const initialLeads: Lead[] = [
  {
    id: 'lead-1',
    buyerName: 'Budi Santoso',
    whatsapp: '628112233445',
    email: 'budi.santoso@techcorp.co.id',
    interestedPropertyId: 'prop-1',
    interestedPropertyTitle: 'Rumah Modern Minimalis 2 Lantai Dekat Kampus UGM',
    source: 'Instagram Ads',
    campaign: 'Sleman Modern Family Home Q3',
    leadTemperature: 'Hot',
    pipelineStage: 'Site Visit',
    assignedSales: 'Dimas Aditya',
    lastActivity: '2026-09-26 14:30',
    createdAt: '2026-09-18',
    notes: 'Karyawan BUMN cari rumah untuk keluarga muda. Suka layout terbuka dan dekat UGM. Siap KPR.',
    minBudget: 700000000,
    maxBudget: 900000000,
    preferredLocation: 'Sleman',
    propertyType: 'House',
    minBedrooms: 3,
    minLandSize: 100,
    paymentMethod: 'KPR',
    buyingPurpose: 'Own Stay',
    purchaseTimeline: '< 3 Months'
  },
  {
    id: 'lead-2',
    buyerName: 'Anindya Putri',
    whatsapp: '6281299887766',
    email: 'anindya.p@designstudio.id',
    interestedPropertyId: 'prop-2',
    interestedPropertyTitle: 'Cluster Scandinavian Asri Dekat RS JIH & Hartono Mall',
    source: 'Facebook Ads',
    campaign: 'Scandinavian Sleman Living',
    leadTemperature: 'Hot',
    pipelineStage: 'Negotiation',
    assignedSales: 'Siti Rahma',
    lastActivity: '2026-09-27 10:15',
    createdAt: '2026-09-15',
    notes: 'Sudah survei 2x bersama suami dan orang tua. Menawar Rp 725 Juta cash bertahap 3x.',
    minBudget: 700000000,
    maxBudget: 800000000,
    preferredLocation: 'Sleman',
    propertyType: 'House',
    minBedrooms: 3,
    minLandSize: 90,
    paymentMethod: 'Cash',
    buyingPurpose: 'Own Stay',
    purchaseTimeline: '< 1 Month'
  },
  {
    id: 'lead-3',
    buyerName: 'H. Surya Pratama',
    whatsapp: '6281355443322',
    email: 'surya.p@pratamagroup.com',
    interestedPropertyId: 'prop-4',
    interestedPropertyTitle: 'Guesthouse / Rumah Mewah Heritage Dekat Malioboro',
    source: 'WhatsApp Inbound',
    campaign: 'Heritage Malioboro Investment',
    leadTemperature: 'Hot',
    pipelineStage: 'Booking',
    assignedSales: 'Dimas Aditya',
    lastActivity: '2026-09-26 17:00',
    createdAt: '2026-09-10',
    notes: 'Investor dari Jakarta. Sudah transfer UTJ (Uang Tanda Jadi) Rp 25 Juta. Jadwal PPJB pekan depan.',
    minBudget: 2500000000,
    maxBudget: 3500000000,
    preferredLocation: 'Kota Yogyakarta',
    propertyType: 'Villa',
    minBedrooms: 4,
    minLandSize: 200,
    paymentMethod: 'Cash',
    buyingPurpose: 'Investment',
    purchaseTimeline: 'Immediate'
  },
  {
    id: 'lead-4',
    buyerName: 'Dian Kusuma',
    whatsapp: '6287733441122',
    email: 'dian.kusuma@gmail.com',
    interestedPropertyId: 'prop-3',
    interestedPropertyTitle: 'Rumah Tropis Modern View Persawahan Asri Kasihan',
    source: 'TikTok Organic',
    campaign: 'Kasihan Sunset Serenity',
    leadTemperature: 'Warm',
    pipelineStage: 'Qualified',
    assignedSales: 'Rian Pratama',
    lastActivity: '2026-09-25 11:20',
    createdAt: '2026-09-21',
    notes: 'Dosen muda UMY, mencari rumah pertama budget 500-600 Juta, DP 20% siap KPR BSI.',
    minBudget: 500000000,
    maxBudget: 620000000,
    preferredLocation: 'Bantul',
    propertyType: 'House',
    minBedrooms: 2,
    minLandSize: 90,
    paymentMethod: 'KPR',
    buyingPurpose: 'Own Stay',
    purchaseTimeline: '< 3 Months'
  },
  {
    id: 'lead-5',
    buyerName: 'Rahmat Hidayat',
    whatsapp: '6281804112233',
    email: 'rahmat.hidayat@pertamina.co.id',
    interestedPropertyId: 'prop-1',
    interestedPropertyTitle: 'Rumah Modern Minimalis 2 Lantai Dekat Kampus UGM',
    source: 'Instagram Ads',
    campaign: 'Sleman Modern Family Home Q3',
    leadTemperature: 'Warm',
    pipelineStage: 'Property Suggested',
    assignedSales: 'Siti Rahma',
    lastActivity: '2026-09-24 16:45',
    createdAt: '2026-09-22',
    notes: 'Kirimkan katalog foto dan spesifikasi detail. Tertarik opsi rumah di Sleman dekat sekolah swasta.',
    minBudget: 800000000,
    maxBudget: 1100000000,
    preferredLocation: 'Sleman',
    propertyType: 'House',
    minBedrooms: 3,
    minLandSize: 110,
    paymentMethod: 'Cash + KPR',
    buyingPurpose: 'Own Stay',
    purchaseTimeline: '3-6 Months'
  },
  {
    id: 'lead-6',
    buyerName: 'Maya Kusumaningrum',
    whatsapp: '6285722339900',
    email: 'maya.kn@advokat.id',
    interestedPropertyId: 'prop-2',
    interestedPropertyTitle: 'Cluster Scandinavian Asri Dekat RS JIH & Hartono Mall',
    source: 'Facebook Ads',
    campaign: 'Scandinavian Sleman Living',
    leadTemperature: 'Cold',
    pipelineStage: 'Contacted',
    assignedSales: 'Rian Pratama',
    lastActivity: '2026-09-23 09:00',
    createdAt: '2026-09-23',
    notes: 'Baru pertama kali dihubungi via WA. Sedang membandingkan dengan perumahan lain di Bantul.',
    minBudget: 650000000,
    maxBudget: 800000000,
    preferredLocation: 'Sleman',
    propertyType: 'House',
    minBedrooms: 2,
    minLandSize: 80,
    paymentMethod: 'KPR',
    buyingPurpose: 'Own Stay',
    purchaseTimeline: 'Exploring'
  }
];

export const initialSiteVisits: SiteVisit[] = [
  {
    id: 'sv-1',
    leadId: 'lead-1',
    buyerName: 'Budi Santoso',
    buyerPhone: '0811-2233-445',
    propertyId: 'prop-1',
    propertyTitle: 'Rumah Modern Minimalis 2 Lantai Dekat Kampus UGM',
    propertyAddress: 'Jl. Kaliurang KM 6.5, Gang Pandega Marta No. 12',
    schedule: '2026-09-28 10:00',
    sales: 'Dimas Aditya',
    status: 'Confirmed',
    notes: 'Survei bersama istri. Titik kumpul di depan Masjid Al-Huda Pandega.',
    buyerFeedback: 'Tertarik sekali dengan lebar jalan cluster dan pencahayaan kamar tidur utama.'
  },
  {
    id: 'sv-2',
    leadId: 'lead-2',
    buyerName: 'Anindya Putri',
    buyerPhone: '0812-9988-7766',
    propertyId: 'prop-2',
    propertyTitle: 'Cluster Scandinavian Asri Dekat RS JIH & Hartono Mall',
    propertyAddress: 'Jl. Palagan Tentara Pelajar KM 9',
    schedule: '2026-09-24 15:30',
    sales: 'Siti Rahma',
    status: 'Completed',
    notes: 'Survei kedua kali bersama kontraktor keluarga untuk estimasi pasang kanopi belakang.',
    buyerFeedback: 'Sangat cocok, lanjut ke tahapan tawar harga dengan pemilik.'
  },
  {
    id: 'sv-3',
    leadId: 'lead-3',
    buyerName: 'H. Surya Pratama',
    buyerPhone: '0813-5544-3322',
    propertyId: 'prop-4',
    propertyTitle: 'Guesthouse / Rumah Mewah Heritage Dekat Malioboro',
    propertyAddress: 'Jl. Bausasran No. 34, Danurejan',
    schedule: '2026-09-22 13:00',
    sales: 'Dimas Aditya',
    status: 'Completed',
    notes: 'Didampingi perwakilan arsitek buyer. Pengecekan struktur bangunan heritage.',
    buyerFeedback: 'Kondisi bangunan terawat, izin homestay lengkap. Deal lanjut booking!'
  }
];

export const initialFollowups: FollowupActivity[] = [
  {
    id: 'fl-1',
    leadId: 'lead-1',
    leadName: 'Budi Santoso',
    assignedSales: 'Dimas Aditya',
    activityType: 'Follow-up',
    scheduledDate: '2026-09-27 15:00',
    status: 'Pending',
    notes: 'Konfirmasi kehadiran survei besok pagi jam 10:00 di Jl. Kaliurang KM 6.5'
  },
  {
    id: 'fl-2',
    leadId: 'lead-2',
    leadName: 'Anindya Putri',
    assignedSales: 'Siti Rahma',
    activityType: 'Negotiation',
    scheduledDate: '2026-09-27 16:30',
    status: 'Pending',
    notes: 'Sampaikan respon pemilik Bu Ratna atas penawaran 725 Juta cash bertahap'
  },
  {
    id: 'fl-3',
    leadId: 'lead-5',
    leadName: 'Rahmat Hidayat',
    assignedSales: 'Siti Rahma',
    activityType: 'WhatsApp',
    scheduledDate: '2026-09-28 09:30',
    status: 'Pending',
    notes: 'Kirim video room tour dan perbandingan skema KPR 15 vs 20 tahun'
  }
];

export const initialBookings: Booking[] = [
  {
    id: 'bk-1',
    leadId: 'lead-3',
    buyerName: 'H. Surya Pratama',
    propertyId: 'prop-4',
    propertyTitle: 'Guesthouse / Rumah Mewah Heritage Dekat Malioboro',
    bookingDate: '2026-09-25',
    bookingAmount: 25000000,
    status: 'Active',
    receiptNumber: 'RCP-HN-2026-098'
  }
];

export const initialClosings: Closing[] = [
  {
    id: 'cls-1',
    propertyId: 'prop-4',
    propertyTitle: 'Guesthouse / Rumah Mewah Heritage Dekat Malioboro',
    leadId: 'lead-3',
    buyerName: 'H. Surya Pratama',
    askingPrice: 3200000000,
    finalSellingPrice: 3100000000,
    closingDate: '2026-10-05',
    commission: 77500000,
    status: 'PPJB Signed'
  }
];

export const initialCommissions: CommissionRecord[] = [
  {
    id: 'com-1',
    propertyId: 'prop-4',
    propertyTitle: 'Guesthouse / Rumah Mewah Heritage Dekat Malioboro',
    ownerName: 'Ir. Hendra Gunawan',
    buyerName: 'H. Surya Pratama',
    sellingPrice: 3100000000,
    commissionType: 'Percentage',
    commissionValue: 2.5,
    earnedAmount: 77500000,
    earnedDate: '2026-10-05',
    paymentStatus: 'Potential',
    invoiceNumber: 'INV-HN-2026-004'
  },
  {
    id: 'com-2',
    propertyId: 'prop-2',
    propertyTitle: 'Cluster Scandinavian Asri Dekat RS JIH & Hartono Mall',
    ownerName: 'Dr. Ratna Susanti',
    buyerName: 'Anindya Putri (In Progress)',
    sellingPrice: 730000000,
    commissionType: 'Percentage',
    commissionValue: 2.5,
    earnedAmount: 18250000,
    earnedDate: '2026-09-30',
    paymentStatus: 'Potential'
  },
  {
    id: 'com-3',
    propertyId: 'prop-hist-01',
    propertyTitle: 'Villa Asri Kaliurang KM 18 View Gunung Merapi',
    ownerName: 'Bambang Soediro',
    buyerName: 'Kusworo Handoko',
    sellingPrice: 1650000000,
    commissionType: 'Percentage',
    commissionValue: 2.5,
    earnedAmount: 41250000,
    earnedDate: '2026-08-20',
    paymentStatus: 'Paid',
    invoiceNumber: 'INV-HN-2026-002'
  },
  {
    id: 'com-4',
    propertyId: 'prop-hist-02',
    propertyTitle: 'Rumah Cantik 1 Lantai Tamanan Banguntapan',
    ownerName: 'Agus Wardoyo',
    buyerName: 'Dra. Endang Lestari',
    sellingPrice: 520000000,
    commissionType: 'Percentage',
    commissionValue: 2.5,
    earnedAmount: 13000000,
    earnedDate: '2026-08-28',
    paymentStatus: 'Paid',
    invoiceNumber: 'INV-HN-2026-003'
  }
];

export const initialPublishing: PublishingRecord[] = [
  {
    id: 'pub-1',
    propertyId: 'prop-1',
    propertyTitle: 'Rumah Modern Minimalis 2 Lantai Dekat Kampus UGM',
    channel: 'Instagram',
    campaignName: 'Sleman Modern Family Home Q3',
    publishDate: '2026-09-08 11:00',
    status: 'Published',
    leadsGenerated: 8,
    contentSnippet: 'Modern Living at its Best ✨ Hunian keluarga favorit di Condongcatur Sleman...',
    externalPostUrl: 'https://instagram.com/p/C-preview-honeyan'
  },
  {
    id: 'pub-2',
    propertyId: 'prop-1',
    propertyTitle: 'Rumah Modern Minimalis 2 Lantai Dekat Kampus UGM',
    channel: 'Facebook Page',
    campaignName: 'Sleman Modern Family Home Q3',
    publishDate: '2026-09-08 11:30',
    status: 'Published',
    leadsGenerated: 6,
    contentSnippet: '🏡 NEW EXCLUSIVE LISTING: Rumah siap huni dekat kampus UGM dengan carport 2 mobil...',
    externalPostUrl: 'https://facebook.com/honeyanproperto/posts/001'
  },
  {
    id: 'pub-3',
    propertyId: 'prop-2',
    propertyTitle: 'Cluster Scandinavian Asri Dekat RS JIH & Hartono Mall',
    channel: 'Instagram',
    campaignName: 'Scandinavian Sleman Living',
    publishDate: '2026-09-12 14:00',
    status: 'Published',
    leadsGenerated: 12,
    contentSnippet: 'Kenyamanan arsitektur Skandinavia di Jl. Palagan KM 9...',
    externalPostUrl: 'https://instagram.com/p/C-scandi-honeyan'
  },
  {
    id: 'pub-4',
    propertyId: 'prop-3',
    propertyTitle: 'Rumah Tropis Modern View Persawahan Asri Kasihan',
    channel: 'TikTok',
    campaignName: 'Kasihan Sunset Serenity',
    publishDate: '2026-09-15 16:30',
    status: 'Published',
    leadsGenerated: 9,
    contentSnippet: 'Room tour rumah 500 jutaan view sawah asri dekat kampus UMY Yogyakarta...',
    externalPostUrl: 'https://tiktok.com/@honeyanproperty/video/99128'
  }
];

export const initialCampaigns: Campaign[] = [
  {
    id: 'cmp-1',
    name: 'Sleman Modern Family Home Q3',
    channel: 'Meta Ads (FB/IG)',
    startDate: '2026-09-05',
    endDate: '2026-10-05',
    properties: ['prop-1'],
    contentAngle: 'Family Home',
    leadCount: 14,
    siteVisitCount: 6,
    closedDeals: 0,
    budget: 3500000
  },
  {
    id: 'cmp-2',
    name: 'Scandinavian Sleman Living',
    channel: 'Meta Ads (FB/IG)',
    startDate: '2026-09-10',
    endDate: '2026-10-10',
    properties: ['prop-2'],
    contentAngle: 'Strategic Location',
    leadCount: 19,
    siteVisitCount: 9,
    closedDeals: 1,
    budget: 4200000
  },
  {
    id: 'cmp-3',
    name: 'Heritage Malioboro Investment',
    channel: 'Google Search',
    startDate: '2026-09-12',
    endDate: '2026-10-15',
    properties: ['prop-4'],
    contentAngle: 'Investment',
    leadCount: 8,
    siteVisitCount: 5,
    closedDeals: 1,
    budget: 5000000
  },
  {
    id: 'cmp-4',
    name: 'Kasihan Sunset Serenity',
    channel: 'Organic Social',
    startDate: '2026-09-15',
    endDate: '2026-10-15',
    properties: ['prop-3'],
    contentAngle: 'First Home Buyer',
    leadCount: 11,
    siteVisitCount: 4,
    closedDeals: 0,
    budget: 1200000
  }
];
