<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HoneyAn.Application\HoneyAn.Application.csproj" />
    <ProjectReference Include="..\HoneyAn.Infrastructure\HoneyAn.Infrastructure.csproj" />
  </ItemGroup>

</Project>
